config/routes.rb
Rails.application.routes.draw do

  # get 'realisations', to: 'pages#realisations', as: 'realisations'
  get 'about_me', to: 'pages#about_me', as: 'about_me'
  get 'contact', to: 'pages#contact', as: 'contact'


  get 'my_admin_space', to: 'work_shops#index', as: 'my_admin_space'
  get 'my_admin_space/:category_id', to: "work_shops#show", as: 'my_admin_show'
  get 'my_admin_space/:category_id/products/:id', to: "work_shops#product_details", as: 'my_admin_product_show'
  # get 'my_admin_space/:category_id/products/:id', to: "work_shops#show", as: 'my_admin_show'

  resources :categories, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  has_one_attached :image

  validates :name, :image, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  has_one_attached :image

  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  has_one_attached :home_image

  # validates :description, presence: true

  validate :max_user_count, on: :create

  def max_user_count
    if User.count === 1
      errors.add(:user, 'Nombre maximum utilisateurs atteint.')
      false
    end
  end
end

app/models/work_shop.rb
class WorkShop < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :image, :description, :home_image, :home_description) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :image, :description, :home_image, :home_description) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save!
      redirect_to my_admin_show_path(@category), notice: "La catégorie '#{@category.name}' a bien été créée."
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to my_admin_space_path, notice: "Les détails de la catégorie '#{@category.name}' ont été modifiés correctement."
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to my_admin_space_path, notice: "La catégorie '#{@category.name}' a bien été supprimée."
  end

  private

  def category_params
    params.require(:category).permit(:name, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :realisations, :about_me, :contact ]

  def home
    return root_path
  end

  def realisations
  end

  def about_me
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show ]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @category = Category.find(params[:category_id])
  end

  def new
    @product = Product.new
    set_category
  end

  def create
    @product = Product.new(product_params)
    @product.category = set_category
    if @product.save!
      redirect_to my_admin_product_show_path(@category, @product), notice: "Le produit '#{@product.name}' a bien été créé."
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to my_admin_product_show_path(@product.category, @product), notice: "Les détails du produit '#{@product.name}' ont été modifiés correctement."
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to my_admin_show_path(@product.category), notice: "Le produit '#{@product.name}' a bien été supprimé."
  end

  private

  def set_category
    @category = Category.find params[:category_id]
  end

  def product_params
    params.require(:product).permit(:name, :description, :image, :category_id)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_update_path_for(resource)
    my_admin_space_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/work_shops_controller.rb
class WorkShopsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :index, :show, :product_details ]
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:category_id])
    @products = Product.all
  end

  def product_details
    @product = Product.find(params[:id])
    @category = Category.find(params[:category_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<div class="admin_form_category">
  <%= simple_form_for [category] do |f| %>
    <%= f.input :name %>
    <%= f.input :image, as: :file %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
  <div class="admin_form_back_btn">
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<div class="categories_cont">

  <% if Category.count >= 1 %>

    <ul class="category_imgs">
      <% @categories.each do |category| %>
        <li class="category_bg_img">
          <%= cl_image_tag category.image.key %>
        </li>
      <% end %>
    </ul>
    <ul class="category_list">
      <% @categories.each do |category| %>
        <li>
          <%= link_to "#{category.name}", category_path(category) %>
        </li>
      <% end %>
    </ul>

  <% end %>

</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="admin_space_title">
  <h1><%= @category.name %></h1>
</div>

<div class="category_show_cont">

  <div class="product_grid">

    <% if Product.count >= 1 %>

      <% @category.products.each do |product| %>
        <%= link_to category_product_path(@category, product) do %>
          <div class="product_card">
            <div class="category_show_img">
              <%= cl_image_tag product.image.key %>
              <div class="hover_dark"></div>
              <div class="hover_txt">
                <div class="hover_info">
                  <strong><%= product.name %></strong>
                </div>
                <br>
                <div class="hover_info">
                  <%= simple_format(product.description) %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Calligraffitti&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Tangerine&display=swap" rel="stylesheet">
    <link rel="icon" href="/favicon.ico">

    <title>Aymeric de Ghellinck d'Elseghem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>

    <% if user_signed_in? %>
      <%= render 'shared/navbar_admin' %>
    <% else %>
      <%= render 'shared/navbar' %>
    <% end %>

    <%= render 'shared/flashes' %>
    <div class="body_cont">
      <%= yield %>
      <div class="bg_darkener"></div>
    </div>

    <% if !user_signed_in? %>
      <%= render 'shared/footer' %>
    <% end %>

  </body>
</html>

app/views/pages/about_me.html.erb
<div class="about_cont">
  <% if User.count === 1 %>

    <div class="about_user_image">
      <%= cl_image_tag User.last.image.key %>
    </div>
    <div class="about_user_description"><%= simple_format(User.last.description) %></div>

  <% end %>
</div>

app/views/pages/contact.html.erb
<div class="contact_cont">
  <ul>
    <li>Prise de rendez-vous par :</li>
    <li> <a href="tel:+32488604832">+32 488 60 48 32</a></li>
    <li><a href="mailto:info.aymeric@aymericdeghellinck.be">info.aymeric@aymericdeghellinck.be</a></li>
    <li>Belgique</li>
  </ul>
</div>

app/views/pages/home.html.erb
<div class="home_cont">

  <div class="image_slider">

    <div class="slides">

      <input type="radio" name="radio-btn" id="radio1">
      <input type="radio" name="radio-btn" id="radio2">
      <input type="radio" name="radio-btn" id="radio3">
      <input type="radio" name="radio-btn" id="radio4">
      <input type="radio" name="radio-btn" id="radio5">

      <% if Product.count >= 5 %>

        <% product_array = [] %>
        <% finding_products = Product.all.sample(5) %>
        <% finding_products.each do |product| %>
          <% product_array << product %>
        <% end %>
        <div class="slide active_image">
          <%= cl_image_tag product_array[0].image.key %>
        </div>
        <div class="slide">
          <%= cl_image_tag product_array[1].image.key %>
        </div>
        <div class="slide">
          <%= cl_image_tag product_array[2].image.key %>
        </div>
        <div class="slide">
          <%= cl_image_tag product_array[3].image.key %>
        </div>
        <div class="slide">
          <%= cl_image_tag product_array[4].image.key %>
        </div>

      <% else %>

        <div class="slide active_image" style="background-color: black;"></div>
        <div class="slide" style="background-color: black;"></div>
        <div class="slide" style="background-color: black;"></div>
        <div class="slide" style="background-color: black;"></div>
        <div class="slide" style="background-color: black;"></div>

      <% end %>

      <div class="navigation-auto">
        <div class="auto-btn1"></div>
        <div class="auto-btn2"></div>
        <div class="auto-btn3"></div>
        <div class="auto-btn4"></div>
        <div class="auto-btn5"></div>
      </div>

    </div>

    <div class="navigation-manual">
      <label for="radio1" id="man_rad1" class="manual-btn"></label>
      <label for="radio2" id="man_rad2" class="manual-btn"></label>
      <label for="radio3" id="man_rad3" class="manual-btn"></label>
      <label for="radio4" id="man_rad4" class="manual-btn"></label>
      <label for="radio5" id="man_rad5" class="manual-btn"></label>
    </div>

  </div>


  <div class="home_info_corner">
    <% if User.count === 1 %>

      <div class="home_user_image">
        <%= cl_image_tag User.last.home_image.key %>
      </div>
      <div class="home_user_description"><%= simple_format(User.last.home_description) %></div>

    <% end %>
  </div>
</div>

app/views/products/_form.html.erb
<div class="admin_form_category">
  <%= simple_form_for [category, product] do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text %>
    <%= f.input :image, as: :file %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
  <div class="admin_form_back_btn">
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form', product: @product, category: @product.category %>

app/views/products/new.html.erb
<%= render 'form', product: @product, category: @category %>

app/views/products/show.html.erb
<div class="product_show_cont">

  <% if Product.count >= 1 %>

    <div class="product_show_img">
      <%= cl_image_tag @product.image.key %>
    </div>

    <div class="product_show_info">

      <div class="product_show_title">
        <h1><%= @product.name %></h1>
      </div>

      <div class="product_show_details">
        <p>
          <strong><em>Description:</em></strong><br>
          <%= simple_format(@product.description) %>
        </p>
      </div>

    </div>

  <% end %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>

  <div class="ghellinckfooter">

    <div class="grid-case">
      <%= link_to "Contact", contact_path %>
    </div>

    <div class="grid-case">
      <div class="empty_div_footer"></div>
    </div>

    <div class="grid-case">
      <a href="https://facebook.com/Aymeric-de-Ghellinck-Artisan-Joaillier-Graveur-106805681245210" target="_blank">Facebook</a>
    </div>

    <div class="grid-case">
      <%= link_to "A propos", about_me_path %>
    </div>

    <div class="grid-case">
      <p>© 2021 <a href="https://www.linkedin.com/in/lazar-istvan/" target="_blank">István Lázár</a> & <a href="https://www.linkedin.com/in/gauthier-wolters-406ba0142/" target="_blank">Gauthier Wolters</a></p>
    </div>

    <div class="grid-case">
      <a href="https://www.instagram.com/adeghellinck_artisan_joaillier/" target="_blank">Instagram</a>
    </div>

  </div>

</footer>

app/views/shared/_navbar.html.erb
<div class="navbar_portfolio">

  <ul class="navbar-links">
    <li class="navbar-item" id="logo_space">
      <%= link_to root_path do %>
        <div id="logo">
          <%#= image_tag("icons/Logo_Aymeric.png", alt: "/") %>
          <%= cl_image_tag("locw6gc6iyjbhavdbmfk") %>
          <div id="logo_name">
            Aymeric de Ghellinck d'Elseghem
          </div>
        </div>
      <% end %>
    </li>
    <li class="navbar-item" id="empty_space">

    </li>
    <li class="navbar-item">
      <%= link_to "Réalisations", categories_path %>
    </li>
    <li class="navbar-item">
      <%= link_to "A propos", about_me_path %>
    </li>
    <li class="navbar-item">
      <%= link_to "Contact", contact_path %>
    </li>
  </ul>
  <div class="logo">
    <%= link_to root_path do %>
      <div class="small_logo">
        <div>
          <%#= image_tag("icons/Logo_Aymeric.png", alt: "/") %>
          <%= cl_image_tag("locw6gc6iyjbhavdbmfk") %>
        </div>
        <div>
          A. de Ghellinck
        </div>
      </div>
    <% end %>
  </div>
  <div class="burger">
    <div class="line1"></div>
    <div class="line2"></div>
    <div class="line3"></div>
  </div>

</div>

<div class="blanc_nav_space"></div>

app/views/shared/_navbar_admin.html.erb
<div class="navbar_portfolio">

  <ul class="navbar-links">
    <li class="navbar-item" id="name">
      <%= link_to "My Work Space", my_admin_space_path %>
    </li>
    <li class="navbar-item" id="empty_space">

    </li>
    <li class="navbar-item">
      <%= link_to "Change admin settings", edit_user_registration_path %>
    </li>
    <li class="navbar-item">
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    </li>
  </ul>
  <div class="logo"><%= link_to "My Work Space", my_admin_space_path %></div>
  <div class="burger">
    <div class="line1"></div>
    <div class="line2"></div>
    <div class="line3"></div>
  </div>

</div>

<div class="blanc_nav_space"></div>

app/views/work_shops/index.html.erb
<div class="admin_space_title">
  <h1>Bienvenue dans ton espace admin</h1>
  <p>Voici les catégories que tu as déjà créées.</p>
</div>

<div class="admin_category_list">
  <ul>
    <% @categories.each do |category| %>
        <li class="admin_list_item">
          <%= link_to my_admin_show_path(category.id) do %>
            <div class="admin_category_card">
              <div class="admin_list_item_name">
                <%= category.name %>
              </div>
              <div class="admin_category_img">
                <%= cl_image_tag category.image.key %>
              </div>
              <div class="admin_category_bg_dark"></div>
            </div>
          <% end %>
          <div class="admin_control_panel">
            <%= link_to edit_category_path(category) do %>
              <i class="far fa-edit"></i>
            <% end %>
            <%= link_to category_path(category), { method: :delete, data: { confirm: "Êtes vous sûr de vouloir supprimer: #{category.name}?" } } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </div>
        </li>
    <% end %>
  </ul>

  <div class="admin_create_btn">
    <%= link_to new_category_path do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>
  </div>
</div>

app/views/work_shops/product_details.html.erb
<div class="admin_space_title" id="product_show_title">
  <h1><%= @product.name %></h1>
  <p>Voici un aperçu de toutes les informations qui seront affichées pour <%= @product.name %>.</p>
  <div class="admin_back_btn">
    <%= link_to my_admin_show_path(@category) do %>
      <i class="fas fa-chevron-left"></i>
    <% end %>
  </div>
</div>

<div class="admin_product_show">
  <% unless !@product.image.attached? %>
    <div class="admin_product_show_img">
      <%= cl_image_tag @product.image.key %>
    </div>
  <% end %>

  <div class="admin_product_show_descritpion">
    <ul>
      <li><strong><em>Nom:</em></strong> <%= @product.name %></li>
      <li><strong><em>Description:</em></strong><br><%= simple_format(@product.description) %></li>
      <li><strong><em>Catégorie:</em></strong> <%= @category.name %></li>
    </ul>
  </div>

  <div class="admin_product_show_btns">
    <%= link_to edit_category_product_path(@category, @product) do %>
      <i class="far fa-edit"></i>
    <% end %>
    <%= link_to category_product_path(@product.category, @product), { method: :delete, data: { confirm: "Êtes vous sûr de vouloir supprimer: #{@product.name}?" } } do %>
      <i class="far fa-trash-alt"></i>
    <% end %>
  </div>
</div>

app/views/work_shops/show.html.erb
<div class="admin_space_title">
  <h1><%= @category.name %></h1>
  <p>Crée, modifie ou visualise les spécificités de tes produits ici.</p>
  <div class="admin_back_btn">
    <%= link_to my_admin_space_path do %>
      <i class="fas fa-chevron-left"></i>
    <% end %>
  </div>
</div>

<div class="admin_product_list">
  <ul>
    <% @category.products.each do |product| %>
      <li class="admin_list_item">
        <%= link_to my_admin_product_show_path(@category, product) do %>
          <div class="admin_product_card">
            <div class="admin_list_item_name">
              <%= product.name %>
            </div>
            <div class="admin_product_img">
              <%= cl_image_tag product.image.key %>
            </div>
            <div class="admin_product_bg_dark"></div>
          </div>
        <% end %>
        <div class="admin_control_panel">
          <%= link_to edit_category_product_path(@category, product) do %>
            <i class="far fa-edit"></i>
          <% end %>
          <%= link_to category_product_path(@category, product), { method: :delete, data: { confirm: "Êtes vous sûr de vouloir supprimer: #{product.name}?" } } do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>

  <div class="admin_create_btn">
    <%= link_to new_category_product_path(@category) do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>
  </div>
</div>